safe: true
lsi: false
highlighter: rouge
markdown: kramdown
url: http://wp-cli.org
permalink: /blog/:title.html
paginate: 10
paginate_path: /blog/page:num
include:
  - _s
exclude:
  - bin
  - Phakefile.php
  - README.md
navigation:
- text: Commands
  url: /commands/
- text: Configuration
  url: /config/
- text: Docs
  url: /docs/
- text: Blog
  url: /blog/
  layout: post
- text: Packages
  url: /package-index/
- text: RESTful WP-CLI
  url: /restful/
